sudo: false

env:
    matrix:
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.4
        - PYTHON_VERSION=3.5

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create --yes -n test python=$PYTHON_VERSION numpy scipy pytest setuptools astropy pip
    - source activate test
    - pip install six

script:
    - py.test gwb

# blocklist
branches:
  except:
  - release
  - exp

